[package]
version = "0.1.0"
name = "sha256-program"
edition = "2021"

[dependencies]
sp1-zkvm = "3.0.0-rc4"
#sha2 = "0.10"
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
